sudo: required
dist: trusty
language: node_js
node_js:
  - '7.6.0'
os:
  - osx
addons:
apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable
    - google-chrome-beta

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
install:
  - npm install -g angular-cli
  - npm install -g karma
  - npm install

before_script:
- ng build

script: 
- xvfb-run karma start config/karma.conf.js --single-run
