sudo: required
dist: trusty
language: node_js
node_js:
  - '7.6.0'
addons:
apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable
    - google-chrome-beta

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
install:
  - npm list -g --depth=0
  - npm install -g npm@latest
  - npm install
  - ls

before_script:
  - ng new projectname
  - cd projectname
  - ng build

script: 
- xvfb-run karma start config/karma.conf.js --single-run
